### ISSUE TITLE
неправильно считается grayscale 

### ISSUE THREAD

**Issue by lunohod-odin** [koteld/ll_images_processing#7]
https://github.com/koteld/ll_images_processing/blob/ed15ed783ab881c10972def462068f2b9b381469/src/main.rs#L8

считаться должно как-то так:
https://en.wikipedia.org/wiki/Grayscale#Converting_color_to_grayscale

**Comment by koteld** [comment]
Существует несколько вариантов реализации grayscale, описанный на Википедии при помощи подсчета линейной интенсивности более правильный, реализую в следующей версии примерно в таком виде:
```
let mut linear_intensity: u8 = 0;
while i + 3 <= length {
    linear_intensity = (0.2126_f32 * pixel_data.offset(i) as u8).saturating_add((0.7152_f32 * pixel_data.offset(i + 1) as u8).saturating_add(0.0722_f32 * pixel_data.offset(i + 1) as u8));
    *pixel_data.offset(i) = linear_intensity;
    *pixel_data.offset(i + 1) = linear_intensity;
    *pixel_data.offset(i + 2) = linear_intensity;
    i += 4;
}
```
